# Data Validation

In [3]:
import pandas as pd ,numpy as np,matplotlib.pyplot as plt,seaborn as sns

In [7]:
df=pd.read_csv("../data/raw/raw_data.csv")

In [12]:
print("Dataset shape:",df.shape)
print("*"*100)
print("Column names:",df.columns.tolist())
print("*"*100)
print("Data types:",df.dtypes)
print("*"*100)
print("Missing values:",df.isnull().sum())
print("*"*100)
print("Duplicate rows:",df.duplicated().sum())
print("*"*100)

Dataset shape: (6362620, 11)
****************************************************************************************************
Column names: ['step', 'type', 'amount', 'nameOrig', 'oldbalanceOrg', 'newbalanceOrig', 'nameDest', 'oldbalanceDest', 'newbalanceDest', 'isFraud', 'isFlaggedFraud']
****************************************************************************************************
Data types: step                int64
type               object
amount            float64
nameOrig           object
oldbalanceOrg     float64
newbalanceOrig    float64
nameDest           object
oldbalanceDest    float64
newbalanceDest    float64
isFraud             int64
isFlaggedFraud      int64
dtype: object
****************************************************************************************************
Missing values: step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64
****************************************************************************************************
Duplicate rows: 0
****************************************************************************************************

In [18]:
for col in df.columns:
    print(f"{col}:{df[col].nunique()}")

step:743
type:5
amount:5316900
nameOrig:6353307
oldbalanceOrg:1845844
newbalanceOrig:2682586
nameDest:2722362
oldbalanceDest:3614697
newbalanceDest:3555499
isFraud:2
isFlaggedFraud:2

In [20]:
df.describe()

,step,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
count,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06
mean,2.433972e+02,1.798619e+05,8.338831e+05,8.551137e+05,1.100702e+06,1.224996e+06,1.290820e-03,2.514687e-06
std,1.423320e+02,6.038582e+05,2.888243e+06,2.924049e+06,3.399180e+06,3.674129e+06,3.590480e-02,1.585775e-03
min,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.560000e+02,1.338957e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2.390000e+02,7.487194e+04,1.420800e+04,0.000000e+00,1.327057e+05,2.146614e+05,0.000000e+00,0.000000e+00
75%,3.350000e+02,2.087215e+05,1.073152e+05,1.442584e+05,9.430367e+05,1.111909e+06,0.000000e+00,0.000000e+00
max,7.430000e+02,9.244552e+07,5.958504e+07,4.958504e+07,3.560159e+08,3.561793e+08,1.000000e+00,1.000000e+00

In [21]:
num_cols = df.select_dtypes(include="number").columns

for col in num_cols:
    print(col, (df[col] < 0).sum())

step 0
amount 0
oldbalanceOrg 0
newbalanceOrig 0
oldbalanceDest 0
newbalanceDest 0
isFraud 0
isFlaggedFraud 0

In [23]:
print(df["isFraud"].value_counts())
df["isFraud"].value_counts(normalize=True) * 100

isFraud
0    6354407
1       8213
Name: count, dtype: int64

isFraud
0    99.870918
1     0.129082
Name: proportion, dtype: float64

In [28]:
print("Original Report:",len(df))
print("Unique:",df["nameOrig"].nunique())

Original Report: 6362620
Unique: 6353307

In [34]:
quality_report = pd.DataFrame({
    "dtype": df.dtypes,
    "missing": df.isnull().sum(),
    "missing_%": df.isnull().mean() * 100,
    "unique": df.nunique()
})

quality_report

                  dtype  missing  missing_%   unique
step              int64        0        0.0      743
type             object        0        0.0        5
amount          float64        0        0.0  5316900
nameOrig         object        0        0.0  6353307
oldbalanceOrg   float64        0        0.0  1845844
newbalanceOrig  float64        0        0.0  2682586
nameDest         object        0        0.0  2722362
oldbalanceDest  float64        0        0.0  3614697
newbalanceDest  float64        0        0.0  3555499
isFraud           int64        0        0.0        2
isFlaggedFraud    int64        0        0.0        2

In [32]:
quality_report["duplicate_count"] = df.duplicated().sum()

In [33]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
step,6362620.0,2.433972e+02,1.423320e+02,1.0,156.00,239.000,3.350000e+02,7.430000e+02
amount,6362620.0,1.798619e+05,6.038582e+05,0.0,13389.57,74871.940,2.087215e+05,9.244552e+07
oldbalanceOrg,6362620.0,8.338831e+05,2.888243e+06,0.0,0.00,14208.000,1.073152e+05,5.958504e+07
newbalanceOrig,6362620.0,8.551137e+05,2.924049e+06,0.0,0.00,0.000,1.442584e+05,4.958504e+07
oldbalanceDest,6362620.0,1.100702e+06,3.399180e+06,0.0,0.00,132705.665,9.430367e+05,3.560159e+08
newbalanceDest,6362620.0,1.224996e+06,3.674129e+06,0.0,0.00,214661.440,1.111909e+06,3.561793e+08
isFraud,6362620.0,1.290820e-03,3.590480e-02,0.0,0.00,0.000,0.000000e+00,1.000000e+00
isFlaggedFraud,6362620.0,2.514687e-06,1.585775e-03,0.0,0.00,0.000,0.000000e+00,1.000000e+00

Dataset shape
Column names
Data types
Missing values
Duplicate rows
Unique values
Numerical ranges
Negative/invalid values
Target distribution (isFraud)
Suspicious/inconsistent records
ID uniqueness
Basic data-quality report

## target relationship

In [36]:
pd.crosstab(df["type"], df["isFraud"])

isFraud         0     1
type
CASH_IN   1399284     0
CASH_OUT  2233384  4116
DEBIT       41432     0
PAYMENT   2151495     0
TRANSFER   528812  4097

In [37]:
pd.crosstab(df["type"], df["isFlaggedFraud"])

isFlaggedFraud        0   1
type
CASH_IN         1399284   0
CASH_OUT        2237500   0
DEBIT             41432   0
PAYMENT         2151495   0
TRANSFER         532893  16

In [39]:
df["type"].value_counts()

type
CASH_OUT    2237500
PAYMENT     2151495
CASH_IN     1399284
TRANSFER     532909
DEBIT         41432
Name: count, dtype: int64

In [42]:
expected = {
    "PAYMENT",
    "TRANSFER",
    "CASH_OUT",
    "DEBIT",
    "CASH_IN"
}

set(df["type"].unique()) - expected

set()

In [43]:
df["isFraud"].unique()

array([0, 1])

In [46]:
df.to_csv(
    "../data/processed/fraud_cleaned.csv",
    index=False
)